In [1]:
import numpy as np
b=np.array([1,5,7,8])
print(b)

[1 5 7 8]


In [4]:
import numpy as np
c=np.array([[1,2,3],[4,6,7]])
print(c)

[[1 2 3]
 [4 6 7]]


In [8]:
import numpy as np
b=np.ones((2,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
import numpy as np
np.random.random((6,7))

array([[0.13635634, 0.22901288, 0.86574402, 0.8643484 , 0.62622652,
        0.63014584, 0.29127049],
       [0.83546014, 0.89787008, 0.60898925, 0.16749763, 0.5537132 ,
        0.66725077, 0.21211187],
       [0.36309279, 0.56955996, 0.05656001, 0.01862915, 0.10921203,
        0.05496404, 0.37415963],
       [0.68019369, 0.80012118, 0.14933814, 0.64885999, 0.73314444,
        0.39284186, 0.05126785],
       [0.09212775, 0.57334307, 0.24394854, 0.70463518, 0.93730329,
        0.37521128, 0.09151602],
       [0.03535405, 0.10798131, 0.87671706, 0.56592879, 0.2528528 ,
        0.37853341, 0.39663518]])

In [11]:
\

import numpy as np
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [12]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
print(b.dtype)

float64


In [16]:
b.astype(np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [17]:
b**2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
b**7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
b==3

array([[False, False, False, False],
       [False, False, False, False]])

In [20]:



np.prod(b,axis=0)

array([1., 1., 1., 1.])

In [21]:
b[0:2,1:2]

array([[1.],
       [1.]])

In [22]:
np.var(b,axis=1)

array([0., 0.])

In [23]:
np.sin(b)

array([[0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098]])

In [24]:


np.exp(b)

array([[2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183]])